# Generated by Django 6.0.3 on 2026-03-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='appearance_mode',
            field=models.CharField(choices=[('light', 'Light'), ('system', 'System'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portal_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
