# Generated by Django 6.0.3 on 2026-03-10 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_userprofile_appearance_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('admin', 'Admin Division'), ('planning', 'Planning Division'), ('construction', 'Construction Division'), ('quality', 'Quality Division'), ('maintenance', 'Maintenance Division')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_division_store_per_user')],
            },
        ),
    ]

