# Generated by Django 6.0.3 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_divisionstore"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedDivisionStore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(choices=[("admin", "Admin Division"), ("planning", "Planning Division"), ("construction", "Construction Division"), ("quality", "Quality Division"), ("maintenance", "Maintenance Division")], max_length=20, unique=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

