# Generated by Django 6.0.3 on 2026-03-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_shareddivisionstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='division',
            field=models.CharField(blank=True, choices=[('admin', 'Admin Division'), ('planning', 'Planning Division'), ('construction', 'Construction Division'), ('quality', 'Quality Division'), ('maintenance', 'Maintenance Division')], max_length=20, null=True),
        ),
    ]
