# Generated by Django 6.0.3 on 2026-03-24 01:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_userprofile_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stored_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='my_app_cons_created_fe6a1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DivisionStoreEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_key', models.CharField(choices=[('admin', 'Admin Division'), ('planning', 'Planning Division'), ('construction', 'Construction Division'), ('quality', 'Quality Division'), ('maintenance', 'Maintenance Division')], max_length=20)),
                ('target', models.CharField(choices=[('shared', 'Shared'), ('user', 'User')], max_length=10)),
                ('write_mode', models.CharField(blank=True, max_length=50)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('stored_payload', models.JSONField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_store_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['store_key', 'created_at'], name='my_app_divi_store_k_e9812e_idx'), models.Index(fields=['actor', 'created_at'], name='my_app_divi_actor_i_624bd7_idx')],
            },
        ),
    ]
