# Generated by Django 6.0.2 on 2026-03-24 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_divisions(apps, schema_editor):
    Division = apps.get_model('my_app', 'Division')
    rows = [
        ('admin', 'Admin Division'),
        ('planning', 'Planning Division'),
        ('construction', 'Construction Division'),
        ('quality', 'Quality Division'),
        ('maintenance', 'Maintenance Division'),
    ]
    for key, label in rows:
        Division.objects.update_or_create(
            key=key,
            defaults={'label': label, 'is_active': True},
        )


def unseed_divisions(apps, schema_editor):
    Division = apps.get_model('my_app', 'Division')
    Division.objects.filter(key__in=['admin', 'planning', 'construction', 'quality', 'maintenance']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_constructionupload_divisionstoreevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('key', models.CharField(choices=[('admin', 'Admin Division'), ('planning', 'Planning Division'), ('construction', 'Construction Division'), ('quality', 'Quality Division'), ('maintenance', 'Maintenance Division')], max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'my_app_division',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceContractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tin', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('philgeps', models.CharField(blank=True, max_length=80, null=True)),
                ('pcab', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('contracts', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=120, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=60, null=True)),
                ('contact_address', models.TextField(blank=True, null=True)),
                ('pcab_license', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_city', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_province', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=60, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'my_app_maintenance_contractor',
            },
        ),
        migrations.RunPython(seed_divisions, unseed_divisions),
        migrations.CreateModel(
            name='MaintenancePersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('division', models.CharField(blank=True, max_length=120, null=True)),
                ('position', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('division_head', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'my_app_maintenance_personnel',
            },
        ),
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True, null=True)),
                ('municipality', models.CharField(blank=True, max_length=120, null=True)),
                ('contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ntp_date', models.DateField(blank=True, null=True)),
                ('contract_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('original_expiry_date', models.DateField(blank=True, null=True)),
                ('additional_cd_days', models.PositiveIntegerField(blank=True, null=True)),
                ('revised_expiry_date', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('revised_contract_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status_previous_percent', models.FloatField(blank=True, null=True)),
                ('status_current_percent', models.FloatField(blank=True, null=True)),
                ('time_elapsed_percent', models.FloatField(blank=True, null=True)),
                ('slippage_percent', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'my_app_construction_project',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=120, null=True)),
                ('model', models.CharField(blank=True, max_length=120, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'my_app_maintenance_equipment',
                'indexes': [models.Index(fields=['status'], name='my_app_main_status_87e3b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('road_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('road_name', models.CharField(max_length=255)),
                ('municipality', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('surface_type', models.CharField(blank=True, max_length=80, null=True)),
                ('length_km', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=60, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'my_app_maintenance_road',
                'indexes': [models.Index(fields=['condition'], name='my_app_main_conditi_e36814_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('road_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=120, null=True)),
                ('priority', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'my_app_maintenance_schedule',
                'indexes': [models.Index(fields=['status', 'start_date'], name='my_app_main_status_edd6e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_admin_record_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('slip_no', models.CharField(blank=True, max_length=64, null=True)),
                ('document_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_type', models.CharField(blank=True, max_length=120, null=True)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('revised_contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('doc_status', models.CharField(default='Draft', max_length=50)),
                ('billing_status', models.CharField(default='Draft', max_length=50)),
                ('scanned_file_url', models.TextField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_division', models.ForeignKey(db_column='assigned_division_key', on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_workflow_records', to='my_app.division')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_records', to=settings.AUTH_USER_MODEL)),
                ('submitted_from_division', models.ForeignKey(blank=True, db_column='submitted_from_division_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_workflow_records', to='my_app.division')),
            ],
            options={
                'db_table': 'my_app_workflow_record',
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('status_after', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_events', to=settings.AUTH_USER_MODEL)),
                ('from_division', models.ForeignKey(blank=True, db_column='from_division_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_from', to='my_app.division')),
                ('to_division', models.ForeignKey(blank=True, db_column='to_division_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_to', to='my_app.division')),
                ('workflow_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='my_app.workflowrecord')),
            ],
            options={
                'db_table': 'my_app_workflow_event',
            },
        ),
        migrations.CreateModel(
            name='QualityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_from', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('particulars', models.TextField(blank=True, null=True)),
                ('doc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_type', models.CharField(blank=True, max_length=120, null=True)),
                ('project_location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_detail', models.TextField(blank=True, null=True)),
                ('scan_url', models.TextField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_recv', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_to_division', models.ForeignKey(blank=True, db_column='route_to_division_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_routes', to='my_app.division')),
                ('workflow_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_record', to='my_app.workflowrecord')),
            ],
            options={
                'db_table': 'my_app_quality_record',
            },
        ),
        migrations.CreateModel(
            name='PlanningRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_no', models.CharField(blank=True, max_length=80, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('revised_contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('budget_allocation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('received_from', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning_record', to='my_app.workflowrecord')),
            ],
            options={
                'db_table': 'my_app_planning_record',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_record_external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('slip_no', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(max_length=255)),
                ('division_label', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='my_app.workflowrecord')),
            ],
            options={
                'db_table': 'my_app_maintenance_task',
            },
        ),
        migrations.CreateModel(
            name='DivisionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_no', models.CharField(blank=True, max_length=80, null=True)),
                ('received_from', models.CharField(blank=True, max_length=255, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(db_column='division_key', on_delete=django.db.models.deletion.RESTRICT, related_name='submissions', to='my_app.division')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_submissions', to=settings.AUTH_USER_MODEL)),
                ('workflow_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_submissions', to='my_app.workflowrecord')),
            ],
            options={
                'db_table': 'my_app_division_submission',
            },
        ),
        migrations.CreateModel(
            name='ConstructionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('construction_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='my_app.constructionproject')),
                ('workflow_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_tasks', to='my_app.workflowrecord')),
            ],
            options={
                'db_table': 'my_app_construction_task',
            },
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='workflow_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_project', to='my_app.workflowrecord'),
        ),
        migrations.AddIndex(
            model_name='workflowrecord',
            index=models.Index(fields=['assigned_division'], name='my_app_work_assigne_4069ba_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrecord',
            index=models.Index(fields=['doc_status', 'billing_status'], name='my_app_work_doc_sta_5fa506_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowevent',
            index=models.Index(fields=['workflow_record', 'acted_at'], name='my_app_work_workflo_03dcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowevent',
            index=models.Index(fields=['to_division', 'acted_at'], name='my_app_work_to_divi_a227a3_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityrecord',
            index=models.Index(fields=['status', 'date_recv'], name='my_app_qual_status_628bab_idx'),
        ),
        migrations.AddIndex(
            model_name='planningrecord',
            index=models.Index(fields=['status', 'date_received'], name='my_app_plan_status_e53099_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['status', 'due_date'], name='my_app_main_status_08bf69_idx'),
        ),
        migrations.AddIndex(
            model_name='divisionsubmission',
            index=models.Index(fields=['division', 'status'], name='my_app_divi_divisio_e72606_idx'),
        ),
        migrations.AddConstraint(
            model_name='divisionsubmission',
            constraint=models.UniqueConstraint(fields=('workflow_record', 'division'), name='my_app_division_submission_unique_record_division'),
        ),
        migrations.AddIndex(
            model_name='constructiontask',
            index=models.Index(fields=['status', 'date_received'], name='my_app_cons_status_12bcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['status_current_percent', 'updated_at'], name='my_app_cons_status__2bf071_idx'),
        ),
    ]
