import os
from importlib.util import find_spec
"""
Django settings for my_site project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read secret key from environment for security; fall back to dev key for local use
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    # Dev-only fallback (do not use in production)
    'dev-secret-key-change-me-3V3d3QhVYq9X1pZk8nT2mR6sL0aC4uF7gJ5wH9eK1rP6xS2dN8bQ',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Toggle DEBUG via environment (default True for local dev)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

# Comma-separated list in DJANGO_ALLOWED_HOSTS (e.g., "example.com,localhost,127.0.0.1")
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = (
    [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
    if _allowed_hosts_env
    else ['localhost', '127.0.0.1', '[::1]']
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'my_app',
]

if find_spec('channels') is not None:
    INSTALLED_APPS.append('channels')

if find_spec('django_celery_beat') is not None:
    INSTALLED_APPS.append('django_celery_beat')

if find_spec('django_celery_results') is not None:
    INSTALLED_APPS.append('django_celery_results')

_has_whitenoise = find_spec('whitenoise') is not None

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if _has_whitenoise:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'my_site.urls'
ASGI_APPLICATION = 'my_site.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_engine = os.environ.get('DJANGO_DB_ENGINE', 'django.db.backends.sqlite3')
_default_db_name = 'peo_database' if _db_engine == 'django.db.backends.mysql' else str(BASE_DIR / 'db.sqlite3')
_db_name = os.environ.get('DJANGO_DB_NAME', _default_db_name)
_db_config = {
    'ENGINE': _db_engine,
    'NAME': _db_name,
}

if _db_engine == 'django.db.backends.mysql':
    _db_config.update({
        'USER': os.environ.get('DJANGO_DB_USER', 'root'),
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', 'Spledelyn1704'),
        'HOST': os.environ.get('DJANGO_DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DJANGO_DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    })

DATABASES = {
    'default': _db_config
}


def _env_int(name, default):
    try:
        return int(os.environ.get(name, str(default)))
    except (TypeError, ValueError):
        return default


_cache_backend = os.environ.get('DJANGO_CACHE_BACKEND', 'django.core.cache.backends.filebased.FileBasedCache')
_cache_location_default = (
    str(BASE_DIR / '.cache' / 'django')
    if _cache_backend == 'django.core.cache.backends.filebased.FileBasedCache'
    else os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')
)
_cache_location = os.environ.get('DJANGO_CACHE_LOCATION', _cache_location_default)
if _cache_backend == 'django.core.cache.backends.filebased.FileBasedCache':
    os.makedirs(_cache_location, exist_ok=True)

CACHES = {
    'default': {
        'BACKEND': _cache_backend,
        'LOCATION': _cache_location,
        'TIMEOUT': _env_int('DJANGO_CACHE_DEFAULT_TIMEOUT_SECONDS', 300),
        'OPTIONS': {
            'MAX_ENTRIES': _env_int('DJANGO_CACHE_MAX_ENTRIES', 5000),
        },
        'KEY_PREFIX': os.environ.get('DJANGO_CACHE_KEY_PREFIX', 'peo'),
    }
}

# App-level cache controls used by dashboard/store view helpers.
SYSTEM_DATA_CACHE_TTL_SECONDS = _env_int('DJANGO_SYSTEM_DATA_CACHE_TTL_SECONDS', 300)
SYSTEM_COMPUTED_CACHE_TTL_SECONDS = _env_int('DJANGO_SYSTEM_COMPUTED_CACHE_TTL_SECONDS', 120)

_redis_url = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': os.environ.get('DJANGO_CHANNEL_LAYER_BACKEND', 'channels_redis.core.RedisChannelLayer'),
        'CONFIG': {
            'hosts': [os.environ.get('DJANGO_CHANNEL_LAYER_URL', _redis_url)],
        },
    }
}

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', _redis_url)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True

CELERY_TIMEZONE = TIME_ZONE


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Use an absolute path so static assets load correctly on nested URLs like
# /accounts/login/ (relative paths would resolve to /accounts/login/static/...).
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
if _has_whitenoise:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = os.environ.get('DJANGO_MEDIA_URL', '/media/')
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT', str(BASE_DIR / 'media')))
DATA_UPLOAD_MAX_MEMORY_SIZE = _env_int('DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE', 262144000)
FILE_UPLOAD_MAX_MEMORY_SIZE = _env_int('DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE', 262144000)

# Production security hardening (enabled only when DEBUG is False)
if not DEBUG:
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() in ('1', 'true', 'yes')
    SECURE_HSTS_PRELOAD = os.environ.get('DJANGO_SECURE_HSTS_PRELOAD', 'True').lower() in ('1', 'true', 'yes')
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False').lower() in ('1', 'true', 'yes')
    SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'False').lower() in ('1', 'true', 'yes')
    CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'False').lower() in ('1', 'true', 'yes')
    if os.environ.get('DJANGO_SECURE_PROXY_SSL_HEADER', '').strip():
        header_name, _, header_value = os.environ['DJANGO_SECURE_PROXY_SSL_HEADER'].partition(':')
        if header_name and header_value:
            SECURE_PROXY_SSL_HEADER = (header_name.strip(), header_value.strip())

_csrf_trusted_origins = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_trusted_origins.split(',') if origin.strip()]
USE_X_FORWARDED_HOST = os.environ.get('DJANGO_USE_X_FORWARDED_HOST', 'False').lower() in ('1', 'true', 'yes')

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
